---

# HPA for backend
# Scales pods between 1 and 5 based on CPU utilization (70%)

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: roberta-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: roberta-backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
